package com.elkei.gol.gui

const val DEFAULT_BOARD_SIZE_X = 20
const val DEFAULT_BOARD_SIZE_Y = DEFAULT_BOARD_SIZE_X
const val MINIMUM_BOARD_SIZE_X = 1
const val MINIMUM_BOARD_SIZE_Y = MINIMUM_BOARD_SIZE_X
const val MAXIMUM_BOARD_SIZE_X = 500
const val MAXIMUM_BOARD_SIZE_Y = MAXIMUM_BOARD_SIZE_X
const val SIMULATION_DELAY_DEFAULT = 500L
const val SIMULATION_DELAY_FASTER_FACTOR = 1.5
const val SIMULATION_DELAY_MINIMUM = 2L
const val SIMULATION_DELAY_MAXIMUM = 3600000L
const val FILE_EXTENSION = "gol"