package com.elkei.gol.gui

const val DEFAULT_BOARD_SIZE_X = 20
const val DEFAULT_BOARD_SIZE_Y = DEFAULT_BOARD_SIZE_X
const val MINIMUM_BOARD_SIZE_X = 1
const val MINIMUM_BOARD_SIZE_Y = MINIMUM_BOARD_SIZE_X
const val MAXIMUM_BOARD_SIZE_X = 100000
const val MAXIMUM_BOARD_SIZE_Y = MAXIMUM_BOARD_SIZE_X